### ISSUE TITLE
Ошибка в расчете налога

### ISSUE THREAD

**Issue by sorgel** [AlexeyKutepov/micex_scripts#1]
Как понимаю, формула дохода исходит из неверного понимания налогообложения купонного дохода:

`bond_yield = (h + c - p) * (1 - tax) = (h + c - [цена покупки] - НКД) * 0.87 =  0.87[разницы цены и номинала) - 0.87(разницы купона и НКД]`

Однако это не так: налог вы заплатите со всего купона, а не только с разницы между купоном и НКД. На доходности этот нюанс скажется очень заметным образом.

http://smart-lab.ru/blog/280176.php

Даже если считать, что в начале следующего года получится вытрясти из налоговой лишнее уплаченное, тем не менее это произойдет минимум через два месяца (а максимум, через 14), после совершения покупки. Насколько легко налоговая соглашается на перасчет я, честно говоря, не знаю.

**Comment by AlexeyKutepov** [comment]
Исправил

**Comment by AlexeyKutepov** [comment]
Поправил расчёты
